### ISSUE TITLE
Fix Telegram webhook for usernames with underscore

### ISSUE THREAD

**Issue by arterialist** [bilde2910/FreeField#10]
There is an issue with webhooks for Telegram with markdown formatting. Research tasks submitted by users with underscores in their nicknames are not posted by the bot.

Steps to reproduce:
1. Add an underscore to username
2. Set up a webhook telegram-compact.md
3. Report any research task matching webhook filters
4. Message won't be posted by the bot

Reason: when there is an underscore in nickname, text of message will be the following - ... ... _user_name_ .....
When such text is sent by the bot with parse_mode="Markdown", Telegram responds with an error that there are unescaped characters and message won't be sent

**Comment by bilde2910** [comment]
Thanks for the report. JSON webhooks are escaped, but apparently Telegram webhooks are treated as plain-text regardless of the format used for the message. I'll make sure to have this patched in the next update, which should be released soon.

**Comment by bilde2910** [comment]
**Status: Partially fixed**

I've resolved the issue and added escapes to the Markdown and HTML message formats for Telegram in v1.0.6. This release has been made available for the general public and you can install the update via the updates section of the admin pages. However, only a partial fix could be implemented to remedy this issue.

Telegram appears to have a bug in their Markdown parsing logic. The string that FreeField sends to Telegram now is properly escaped (e.g. "sample_user" becomes `sample\_user`). However, if the character that is escaped is somehow wrapped in syntax that correctly uses that character to alter the text formatting - in this case, if the username is italicised because it's wrapped in underscores - the escaping does not seem to take effect. That is to say, `sample\_user` is recognized as valid Markdown by Telegram, but `_sample\_user_` is *not* accepted by Telegram even though the string is syntactically correct. Wrapping the text in other characters instead (e.g. `*sample\_user*`) works, but parses the backslash as a literal character, resulting in "**sample\\_user**".

As far as I can tell, there is no way for me to fix this further on my end, so my suggested fix to you will be either recreating the Telegram webhooks using the new HTML presets in v1.0.6 - these look exactly the same as in v1.0.5 but use HTML instead - or to update your existing webhooks to use the HTML parse mode instead of Markdown, and replacing the body of the webhooks with the contents of either of the [new HTML presets here](https://github.com/bilde2910/FreeField/tree/master/includes/hook-presets/telegram). If you don't want to switch, you can update to v1.0.6 and remove the `_` wrapping of the "reported by" line of the webhook body, but this will of course change the visual appearance of the message.
