### ISSUE TITLE
Error message when adding Pokéstops

### ISSUE THREAD

**Issue by ghost** [bilde2910/FreeField#11]
First I would like to tell you that you're doing an amazing job with this project.

Right now I'm testing the map on a free hosting, all steps for the installation went with green checks and without issues, but when I try to add a Pokéstop, I get an error message saying:
"Failed to add new Pokéstop "(name)": Unknown reason"
I'm confused as what to do. I've read the docs but I haven't found something regarding about that error.
One thing I guess, it could probably be, but I'm not sure, https is red and marked as "Not Secure"

I would like to test and get everything working, and if everything goes Ok, I'm planning to make it live for the communities in my City.
Because right now, some friends and me, we are using Google Maps and adding manually the reports in there, and sometimes it get's a bit tiring.

And one last thing.
You think it would be possible to add Facebook as part of the login options??

Thanks for your hard work.

**Comment by bilde2910** [comment]
Hi there! Thanks for the inquiry and for the positive feedback.

Given that you say you've got a red "https" in the address bar, the most likely issue is that HTTPS isn't properly set up with a valid certificate on the web host - if you just set up the hosting, it might be that your host hasn't assigned you a certificate yet (although this *should* usually go very quickly).

One thing that would help pinpoint what the issue is if you could open the developer console (F12) on your site and check for any errors that may pop up in either the Console tab or Network tab when you try to add a Pokéstop. Feel free to put the errors here if you want help with them. In particular, if you can find any status codes (200, 300, 400, 500, etc.) in the Network tab, that can help with determining where to go next.

As for Facebook logins; I might be able to pull that off, but I'm not very familiar with how their sign-ins work. I'll add it to my queue and take a look once I've got time and see what I can do.

**Comment by ghost** [comment]
Hey!

You think it can probably be because I'm using a free domain?... (I'm using .ga right now)
Because If I see the info from the certificate, it shows info from the hosting, and it says is active and secure.
But can this "error" make any issues with other people reporting tasks or something like that in the future??

I will attach screenshots from Console and Network tabs:
( https://user-images.githubusercontent.com/47486241/52527831-3a3bdc80-2c9d-11e9-9ca1-66a4359618aa.png )
( https://user-images.githubusercontent.com/47486241/52527833-3b6d0980-2c9d-11e9-9582-9e274ea981ee.png )
Let me know if you need more info.

About the Facebook login, that would be really awesome if you are able to add it, since not many people in my community uses Discord or Reddit. But I think I can persuade them to start using it.

Thanks for your answer.

Edit1:
Searching about the issue with the certificate, I found that the hosting only let their free domains ( X.hosting.com ) use SSL, and personal domains with their nameserver would mostly show as "Not Secure, or invalid certificate".
And they created a small guide for people who wanted their personal domains work without problems with SSL, and that way is connecting the domain to CloudFlare.

I already did that, and no longer shows as "Not secure", but I still have the problem with creating Pokéstops.
I get this error now:
( https://user-images.githubusercontent.com/47486241/52530086-52c3eb00-2ccd-11e9-8979-084ce09a1e76.png )

**Comment by bilde2910** [comment]
I've been able to reproduce the issue. For now it looks like your host has misconfigured something. I'll see if I can work around it and will update you if I find anything.

**Comment by bilde2910** [comment]
If you're using a particular web hosting company whose name starts with three zeroes, then this seems to be an intentional limitation by them in order to make you pay for hosting. If you're able to, I would consider looking for another web hosting company instead. (I would also avoid OVH if I were you; I've heard of others having issues with them, and they haven't been willing to respond to tickets/inquiries when I've tried troubleshooting the project there.)

**Comment by ghost** [comment]
Yeah, I created the account on 00webhost, because I tried 2 other hostings before them, but they had the function fopen() disabled.
I'll try to look for another web hosting and keep you updated if anything else happens.

Thanks for your answers.

Update:
My brother had a paid hosting, so I asked him if he could give me a space to test it out. And now everything with green checks, map is working like a charm.

**Comment by bilde2910** [comment]
Good to hear you resolved it, at least for now. I will look at removing the fopen() dependency as well. It's something that isn't strictly required to make it work, as cURL (which does work) can be used for the same thing as what I use fopen() for. I wasn't aware of the extent that fopen() was disabled on public hosting, so removing it should help improve compatibility quite a bit. That should make it easier for you to find a place that can host it. (By the way, when you use free hosting, make sure you take periodic exports of your Pokéstops list. Free hosting may lead to stability issues down the road, and I've had my share of those from when I was using 000. Having a recent backup on hand could save you a lot of time should problems arise.)

Thank you for identifying the fopen() issue. I will mark this one (#11) as invalid, as it strictly speaking isn't an issue in FreeField itself, but the fopen() issue definitely qualifies as a bug on its own, so I will create a new issue for that. Feel free to subscribe to #12, linked below, and you'll receive a notification when I've patched it.

**Comment by ghost** [comment]
Yeah, I'm with a lended space on a paid hosting, everything runs okay, zero problems as for now.

Maybe you could try adding an option to choose between cURL or fopen() at the first page of the installation (if it possible to easily choose wich one to use).
I remember reading in their forums, that fopen() were only enabled for paid hostings, and disabled for free hosting as a security measurement.

(Thanks for the recommendation I will do that periodically)
By the way, there are a few things I would like to ask you about the map, and a few that could be small enhancements, or that can speed up a few things.
I showed the map and many features to my friends and they really loved it, we are in the process of importing the Pokéstop's made on Google Maps, and then we are going to have something like a "closed beta".

**Comment by bilde2910** [comment]
cURL is already a requirement anyway because it's used by a dependency of FreeField. My goal with fopen() is to make HTTP requests, and the cURL and fopen() methods are just two ways to achieve that goal; I just decided on using fopen() when making FreeField since it's the method I'm the most familiar with. But generally, cURL is considered the [better option](https://stackoverflow.com/questions/11064980/php-curl-vs-file-get-contents) of the two. fopen() is a method designed for reading files, while cURL is a method designed for making HTTP requests; fopen() just also happens to work for the latter case if you give it a URL rather than a filename, but requires that fopen() reading from URLs is enabled on the host. Since cURL is a much more powerful option and I'd rather not rewrite the code of the dependency, it makes more sense to just migrate to cURL and drop the fopen() requirement entirely.

I gladly welcome questions and enhancements about the map! Feel free to open more issues here about whatever you wish. I'm also available via direct messaging on Discord (bilde2910#6809) if that's an easier way for you to reach out for questions etc.
