### ISSUE TITLE
Show Gyms on the map

### ISSUE THREAD

**Issue by stevear22** [bilde2910/FreeField#2]
Although Gyms don't give field research, it'd be nice to have them on there as a visual reference or landmark.

**Comment by bilde2910** [comment]
This sounds like a good idea. I will have to figure out how to implement this technically, and also design a marker that can be used to represent gyms. A compass-style icon would blend in too much with the existing research markers, and it can't be a carbon copy of the in-game gym marker icon either. There's also the question of whether gyms should be more than just markers - think egg and raid reporting, with associated webhooks and notifications - but that would be a major overhaul, so that at least won't happen until well after stable 1.0.

I'll see what I can do to have this feature added, though it might take a while to actually implement due to the required work. I can't guarantee that it will be added right away, so I'll leave this issue open for a while until I've cleared up a few other things that have higher priority.

**Comment by bilde2910** [comment]
Just a quick status update: This will not be added in 1.0, as by now I just need to get this released and out there in the world as quickly as possible. I'm looking at adding this in 1.1, though, as it is a feature that several of the testers have suggested.

**Comment by stevear22** [comment]
After using FreeField in its current form, I'd say that PokeStops not showing is not hindering the experience at all.  For me, at least, this seems low priority.

**Comment by Foxpire** [comment]
Great tool to inform field research to local community. Some field researches cannot be updated when using mobile browser. Those researches have this kind form "do something, get n something as reward". But using desktop all goes well. That could actually be hardware/serverside issue since I'm hosting own server.

How big task it would be to fork this to be raidtool?

**Comment by bilde2910** [comment]
Hi @Foxpire and thanks for the feedback! If you've encountered issues/bugs then I'd be very grateful if you could create a new issue here on the issue tracker with as many details as possible - which exact research you are trying to submit, with what parameters, what error you are getting (or what else is happening if you do not get an error message), which browser, device and OS (and version) you are experiencing this on, etc. That will hopefully help me narrow down the problem and resolve the issue.

Gym markers is something that has been planned for a while, and I've tried coming up with some decent designs for the markers, but I don't have anything conclusive yet. I do plan to start working more actively on this feature in about a week or so, so I can finish up with university projects that I'm currently working on before I start.

Raid reporting would be an interesting addition, but there is a question of how alerts would best be handled. It's not possible to easily schedule alerts to be broadcast when an egg hatches, for example, due to the way PHP scripting works. There will also be more work keeping an up-to-date list of raid bosses that are active at any given time, given that these frequently change and there is, as far as I know, no actively updated list of bosses that I can easily fetch this data from automatically. A lot of communities also already have other bots that takes care of the raid reporting and associated sign-ups and alerting. Raid reporting might come at a later date depending on how much interest there is in implementing that as a feature in FreeField.

**Comment by bilde2910** [comment]
Support for gyms has now been added to release v1.2-alpha.1. You can update to this release to test it, but keep in mind that this is an alpha release and may not be suitable for a production environment at this time.
