### ISSUE TITLE
Don't allow Site Host to demote themselves

### ISSUE THREAD

**Issue by stevear22** [bilde2910/FreeField#4]
Carelessness led me to find this bug... I was mass updating permissions and accidentally demoted myself from Site Host to Administrator... I was allowed to do it and now I don't have access to change it back =\

Luckily I do have someone else as a Site Host... but it leads me to this enhancement request - while I have not tested removing the only Site Host, there should be some logic in there that prevents the last Site Host from being removed... or maybe a popup that says 'are you sure you want to do this?'.

Congrats on the 1.0 release!!

**Comment by bilde2910** [comment]
Thanks for the report! This is actually something that I didn't consider, and a pretty serious issue because re-instating a site host when there are no site hosts left isn't straightforward. The way you'd have to fix it if the last site host was demoted would be to access the database directly and change the permission level of your user account to [250](https://freefield.readthedocs.io/en/latest/permissions.html#default-groups), corresponding to the site host group.

Site hosts can demote themselves in the event that they want to transfer ownership to another user, but there are unfortunately no measures in place to ensure they actually *transfer* rather than leaving nobody else in the group. I will change this in the next update to lock the group selector for the currently signed in user by default, requiring you to click on a button and acknowledge a warning before allowing your own group to be changed. That should prevent this from happening again in the future.
