### ISSUE TITLE
Identify which Pokémon encounter is rewarded on the map and webhooks

### ISSUE THREAD

**Issue by stevear22** [bilde2910/FreeField#5]
It would be nice to visually see an icon of the Pokémon that is rewarded.  Encounter tasks currently show the default encounter.svg on the map and in webhooks (REWARD_ICON).

**Comment by bilde2910** [comment]
This would be ideal. Figuring out copyright and usage terms for sprites is the hard part here. I've seen that there are other Pokémon Go-related projects which do use sprites. Perhaps I could reach out to them for advice.

I could definitely add Pokédex *numbers* to the map but I figure that's not really the best way forward. I'll keep you up to date on what I find out.

**Comment by bilde2910** [comment]
I think I found a good compromise here. The icons will not feature the Pokémon sprites themselves as the copyright and trademarks for those are a bit tricky. Instead, I can resolve to adapting the generic encounter.svg with colors that roughly match the species in question and which feature the species' name and ID, as previously discussed. Here's a preview of what the marker for e.g. Spinda would look like:

![spda-icon](https://user-images.githubusercontent.com/6617815/52476192-337a7000-2b9e-11e9-84c2-bfb8fedba791.png)

Hopefully these are recognizable enough on the map that it's easy to tell at a glance which species the research task would award. In cases where there are several possible rewards, it could either cycle/fade between them, or just show the generic encounter.svg as a replacement.

I'm aware that making just shy of 500 variations of this will take quite a long time, but if it looks good then I'd be glad to put down that effort, which I'd probably have to do either way (and I might be able to script it to some extent).

Let me know what you think about this style of icons.

**Comment by stevear22** [comment]
I think it looks good.. but I shudder at the thought of marking these
individually.  It might be worth the effort to try to do this
programmatically with overlays or something or dynamically generated SVGs
or something.

We have gotten our discord notifications to display the proper icon, so
people are able to scroll through the daily tasks and easily pinpoint what
they are looking for.  I still think this would be a valueable addition to
the map, but don’t kill yourself over it.

**Comment by bilde2910** [comment]
I fortunately won't have to make all of them individually. Since I'm making these in vector format, I can modify the source programmatically and insert the necessary name, ID, colors etc without having to click and point in Inkscape. Once that part is done, I'll have to eliminate the dependency on font files and also export to PNG. Inkscape has some nice command line options which I hope can achieve this as well via bash scripting.

**Comment by bilde2910** [comment]
This feature has now been fully implemented. I resorted to using shades of a single color instead of two separate colors for the icons. It worked well for Spinda, but rather poorly for most of the others, unfortunately.

The update is now live in v1.1-alpha.1, which can be installed from the updates section of the admin pages. If you use `git pull` to install updates, note that this release has been built from the `dev` branch rather than `master`, as it is an unstable release.
